
# This build will be awfully slow

OPTS            := -O3 

OTHERLIBS	:= 

WEIGHTS	:= $(subst .cpp,.o,$(wildcard ../data/weights*.cpp))

test:	main.cpp tensor.hpp model.hpp weights.a Makefile.generic
	g++ ${OPTS} main.cpp weights.a -o $@ -lsndfile ${OTHERLIBS}

weights.a: ${WEIGHTS}
	ar rc $@ $^

clean:
	rm test
