
OPTS 	:= -O3 -DUSE_CBLAS -DUSE_ACCELERATE -DUSE_DISPATCH -DACCELERATE_NEW_LAPACK=1 -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers

OTHERLIBS	:= -framework Accelerate

test:	main.cpp tensor.hpp model.hpp Makefile.macos
	g++ ${OPTS} main.cpp ../data/weights.a -o $@ -lsndfile ${OTHERLIBS}

clean:
	rm test
