
OPTS 	:= -O3 -DUSE_CBLAS -DUSE_ACCELERATE -DUSE_DISPATCH -DACCELERATE_NEW_LAPACK=1 -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers

OTHERLIBS	:= -framework Accelerate

WEIGHTS	:= $(subst .cpp,.o,$(wildcard ../data/weights*.cpp))

test:	main.cpp tensor.hpp model.hpp weights.a Makefile.macos
	g++ ${OPTS} main.cpp weights.a -o $@ -lsndfile ${OTHERLIBS}

weights.a: ${WEIGHTS}
	ar rc $@ $^

clean:
	rm test
